/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'openAiSentimentAnalyzer': EventHandler<{ text: string }, { topic: 'openai.positiveSentiment'; data: { sentiment: string; analysis?: string; advice?: string } } | { topic: 'openai.negativeSentiment'; data: { sentiment: string; analysis?: string; advice?: string } }>
    'handlePositive': EventHandler<{ sentiment: string; analysis?: string; advice?: string }, never>
    'handleNegative': EventHandler<{ sentiment: string; analysis?: string; advice?: string }, never>
    'analyzeSentimentApi': ApiRouteHandler<{ text: string }, unknown, { topic: 'openai.analyzeSentimentRequest'; data: { text: string } }>
  }
}